services:
  mysql:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    networks:
      - portfolio-network
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    secrets:
      - mysql_root_password
      - mysql_password

  api:
    depends_on:
      - mysql
    build:
      context: ./api
      target: dev
    working_dir: /app
    networks:
      - portfolio-network
    ports:
      - "3001:3001"
    volumes:
      - ./api:/app
      - go-pkg-mod:/root/go/pkg/mod
    environment:
      MYSQL_HOST: mysql:3306
      MYSQL_USER: devsite_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_DATABASE: devsite_db
    secrets:
      - mysql_password

  app:
    build:
      context: ./app
      target: dev
    working_dir: /app
    networks:
      - portfolio-network
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app
      - /app/node_modules

networks:
  portfolio-network:

secrets:
  mysql_root_password:
    file: secrets/mysql_root_password.txt
  mysql_password:
    file: secrets/mysql_password.txt

volumes:
  mysql_data:
  go-pkg-mod:
