services:
  mysql:
    build:
      context: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    secrets:
      - mysql_root_password
      - mysql_password

  app:
    network_mode: "host"
    depends_on:
      - mysql
    build:
      context: .
      target: prod
      network: host
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
      - /app/secrets
    environment:
      MYSQL_HOST: localhost:3306
      MYSQL_USER: devsite_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_DATABASE: devsite_db
    secrets:
      - mysql_password

secrets:
  mysql_root_password:
    file: secrets/mysql_root_password.txt
  mysql_password:
    file: secrets/mysql_password.txt

volumes:
  mysql_data:
